services:
  app:
    container_name: lsby-kasm-core
    # image: lsby/kasm-core:ubuntu-22-04
    build:
      context: .
      dockerfile: dockerfile-kasm-core
    ports:
      - 6901:6901
    volumes:
      - ./docker-kasm-core/:/home/kasm-user
    # network_mode: "host"
    restart: unless-stopped
